### ISSUE TITLE
We call inner for paged queries as well 

### ISSUE THREAD

**Issue by slivne** [haaawk/scylla-java-driver-tools#1]
https://github.com/haaawk/scylla-java-driver-tools/blob/84f34d0bacaf77a795040f7d2f0383642eba346c/scylla-java-driver-tools-lib/src/main/java/com/scylladb/driver/tools/PagingOptimizingLoadBalancingPolicy.java#L73

It may be better tdo this only when there is a need - so first requests will still be balanced by inner policy correctly (e.g. roundrobin)

**Comment by haaawk** [comment]
The first request will be balanced by inner policy. Every Session#execute
and the like are wrapping the statement that it is executing into a new
PagingOptimizingStatement
<https://github.com/haaawk/scylla-java-driver-tools/blob/84f34d0bacaf77a795040f7d2f0383642eba346c/scylla-java-driver-tools-lib/src/main/java/com/scylladb/driver/tools/PagingOptimizingStatement.java>
which will have lastHost equal to null.
Only after the first successful request lastHost will be set and used for
every consecutive request for this particular execution only.

Please let me know if you have any questions about this.

**Comment by haaawk** [comment]
I think it is required to call inner anyway because this query plan is also used for speculative executions and in case lastHost gets unreachable or timeouts.
